# llamafactory-cli export bash_script/export_model/temp_auto_merge_dpo_ta_llama3_instruct_dpo_list_bsz1_trible_debug_v1-1500.yaml
# llamafactory-cli export bash_script/export_model/temp_auto_merge_dpo_tulu_v2_8b_default_template_dpo_list_bsz1_trible_debug_v4-1500.yaml
# llamafactory-cli export bash_script/export_model/temp_auto_merge_dpo_tulu_v2_8b_default_template_dpo_list_bsz1_trible_debug_v5-1500.yaml
# llamafactory-cli export bash_script/export_model/temp_auto_merge_dpo_tulu_v2_8b_default_template_dpo_list_bsz1_trible_debug_v6-1500.yaml
# llamafactory-cli export bash_script/export_model/temp_auto_merge_dpo_tulu_v2_8b_default_template_dpo_list_bsz1_trible_debug_v8-1500.yaml
# llamafactory-cli export bash_script/export_model/temp_auto_merge_dpo_ta_llama3_instruct_dpo_list_bsz1_trible_debug_v1-1500.yaml
# llamafactory-cli export bash_script/export_model/temp_auto_merge_dpo_ta_llama3_instruct_dpo_list_bsz1_trible_debug_v1.yaml
# llamafactory-cli export bash_script/export_model/temp_auto_merge_dpo_tulu_v2_8b_default_template_dpo_list_bsz1_trible_debug_v7-1500.yaml
# llamafactory-cli export bash_script/export_model/temp_auto_merge_dpo_ta_llama3_instruct_dpo_list_bsz1_trible_debug_v2.yaml
# llamafactory-cli export bash_script/export_model/temp_auto_merge_dpo_ta_llama3_instruct_dpo_list_bsz1_trible_debug_v4-1500.yaml
# llamafactory-cli export bash_script/export_model/temp_auto_merge_dpo_ta_llama3_instruct_dpo_list_bsz1_trible_debug_v4.yaml
# llamafactory-cli export bash_script/export_model/temp_auto_merge_dpo_ta_llama3_instruct_dpo_list_bsz1_trible_debug_v5-1500.yaml
# llamafactory-cli export bash_script/export_model/temp_auto_merge_dpo_ta_llama3_instruct_dpo_list_bsz1_trible_debug_v5.yaml
llamafactory-cli export bash_script/export_model/temp_auto_merge_dpo_tulu_v2_8b_default_template_dpo_list_bsz1_trible_debug_v9-1500.yaml
# llamafactory-cli export bash_script/export_model/temp_auto_merge_tulu_sft_uf_ta_dpo-1000.yaml
# llamafactory-cli export bash_script/export_model/temp_auto_merge_tulu_sft_uf_ta_dpo.yaml
# llamafactory-cli export bash_script/export_model/temp_auto_merge_dpo_tulu_v2_8b_default_template_dpo_list_bsz1_trible_debug_v10-1500.yaml