llamafactory-cli export bash_script/export_model/merge_dpo_llama3.1_instruct_tarejected_v2-1000.yaml
llamafactory-cli export bash_script/export_model/merge_dpo_llama3.1_instruct_tarejected_v2-500.yaml
llamafactory-cli export bash_script/export_model/merge_dpo_default_template_2048_ta_rejected_v2_500.yaml
llamafactory-cli export bash_script/export_model/merge_dpo_default_template_2048_ta_rejected_v2_1000.yaml