### model
model_name_or_path: model/bitnet-2B-v0/

### method
stage: sft
do_train: true
finetuning_type: full
flash_attn: fa2
# deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: glan1.5
template: bitnet
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
# streaming: true
# split_batches: true

### output
output_dir: /mnt/lingjiejiang/textual_aesthetics/exp/saves/bitnet_glan1.5_2048_default_template/lr2e5_e3_bsz2k_fx/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 32
learning_rate: 2.0e-5
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
num_train_epochs: 3.0


### eval
val_size: 1000
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 1000
