### model
model_name_or_path: /mnt/lingjiejiang/textual_aesthetics/model_checkpoint/sft_merge_checkpoints/gemma-2-9b-it

### method
stage: dpo_list
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: hinge  # choices: [sigmoid (dpo), orpo, simpo]
list_dpo_method: v2

### dataset
dataset: ta_list_dpo_job
template: gemma
cutoff_len: 2048
max_samples: 64000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/lingjiejiang/textual_aesthetics/exp/saves/gemma-2-9b-it_tapo_v2/lora/dpo
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
report_to: tensorboard

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
