### model
# model_name_or_path: /mnt/lingjiejiang/textual_aesthetics/exp/saves/magpie_8b_2048_default_template/fullft_lr2e5_e2/sft/checkpoint-536
model_name_or_path: /mnt/lingjiejiang/textual_aesthetics/exp/saves/glanchat_v2.1_8b_2048_default_template/fullft_lr5e6_e3/sft/checkpoint-9918

### method
stage: dpo
do_train: true
finetuning_type: full
pref_beta: 0.01
flash_attn: fa2
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: magpie_dpo_v0.1
template: default
cutoff_len: 2048
max_samples: 200000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/lingjiejiang/textual_aesthetics/exp/saves/magpie_dpo_v0.1_8b_2048_default_template_dpo_glanchatv2.1_ckpt9918/fullft/dpo
logging_steps: 1
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train #bsz 128
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-7
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.001
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
