### model
model_name_or_path: /mnt/lingjiejiang/textual_aesthetics/model_checkpoint/bitnet-2B-v0/

### method
stage: sft
do_train: true
finetuning_type: full
flash_attn: fa2
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: glan1.5
template: default
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16


### output
# output_dir: /mnt/lingjiejiang/textual_aesthetics/exp/saves/bitnet_glan1.5/bitnet_glan1.5_default_template_2e5_e2_bsz128_trm4442
output_dir: /mnt/lingjiejiang/textual_aesthetics/exp/saves/bitnet_glan1.5/bitnet_glan1.5_default_template_5e6_e4_bsz128
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
num_train_epochs: 4.0


### eval
val_size: 1000
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 1000
