### model
# model_name_or_path: /mnt/lingjiejiang/textual_aesthetics/exp/saves/bitnet_magpie_2048_default_template/lr2e5_e2_bsz2k/sft/checkpoint-536/
model_name_or_path: model/checkpoint-6000/

### method
stage: dpo
do_train: true
finetuning_type: full
pref_beta: 0.01
flash_attn: fa2
# deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: magpie_dpo_v0.1
template: default
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/lingjiejiang/textual_aesthetics/exp/saves/bitnet_glan1.5/bitnet_glan1.5_default_template_2e5_e2_bsz128_trm4442_dpo_bsz128_2e7_1e_6000ckpt_nods
logging_steps: 1
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train #bsz 128
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 2.0e-7
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.001
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
