### model
model_name_or_path: /mnt/lingjiejiang/textual_aesthetics/exp/saves/bitnet_glan1.5/bitnet_2b_2t_sft_glan1.5_5e-6_8k_4ep_chatformat_loss/

### method
stage: dpo
do_train: true
finetuning_type: full
pref_beta: 0.01
flash_attn: fa2
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: magpie_dpo_v0.1
template: bitnet_default
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/lingjiejiang/textual_aesthetics/exp/saves/bitnet_glan1.5/bitnet_2b_2t_sft_glan1.5_5e-6_8k_4ep_chatformat_loss_dpo_bsz32_2e7_1e_bitnet_default
logging_steps: 1
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train #bsz 128
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 2.0e-7
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.001
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
