### model
model_name_or_path: /mnt/lingjiejiang/math_reason/exp/model_lr1e-5_batch512_epochs3_gpus8_linearSchedule/checkpoint-402/

### method
stage: dpo
do_train: true
finetuning_type: full
pref_beta: 0.01
flash_attn: fa2
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: qwq_math_1220
template: alpaca
cutoff_len: 2048
max_samples: 200000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /mnt/lingjiejiang/math_reason/exp/1220_dpo_data/bsz64_lr2e7_e1
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train #bsz 128
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 2.0e-7
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.001
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 100
